# Generated by Django 6.0 on 2026-01-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_items_description_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, help_text='ex: 1kg, 500g, 250ml', max_length=50, null=True),
        ),
    ]
